package oasis.names.tc.dss._1_0.core.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-11-15T13:06:53.776-06:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "urn:oasis:names:tc:dss:1.0:core:wsdl", name = "SOAPport")
@XmlSeeAlso({oasis.names.tc.dss._1_0.profiles.archive.ObjectFactory.class, oasis.names.tc.dss._1_0.profiles.xss.ObjectFactory.class, oasis.names.tc.dss._1_0.profiles.dss_pdf.ObjectFactory.class, org.etsi.uri._01903.v1_2.ObjectFactory.class, org.w3._2000._09.xmldsig.ObjectFactory.class, oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, org.oasis_open.docs.dss.oasis_dss_1.ObjectFactory.class, oasis.names.tc.saml._2_0.assertion.ObjectFactory.class, org.etsi.uri._02231.v1.ObjectFactory.class, oasis.names.tc.dss._1_0.profiles.asynchronousprocessing._1.ObjectFactory.class, org.w3._2001._04.xmlenc.ObjectFactory.class, org.etsi.uri._2038.v1_1.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class, oasis.names.tc.dss._1_0.profiles.compound.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SOAPport {

    @WebResult(name = "ArchiveDeleteResponse", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:archive", partName = "ArchiveDeleteResponse")
    @WebMethod
    public oasis.names.tc.dss._1_0.profiles.archive.ArchiveDeleteResponse archiveDelete(
        @WebParam(partName = "ArchiveDeleteRequest", name = "ArchiveDeleteRequest", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:archive")
        oasis.names.tc.dss._1_0.profiles.archive.ArchiveIdentifierRequest archiveDeleteRequest
    );

    @WebResult(name = "ArchiveModifyResponse", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:archive", partName = "ArchiveModifyResponse")
    @WebMethod
    public oasis.names.tc.dss._1_0.core.schema.ResponseBaseType archiveModify(
        @WebParam(partName = "ArchiveModifyRequest", name = "ArchiveModifyRequest", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:archive")
        oasis.names.tc.dss._1_0.profiles.archive.ArchiveIdentifierRequest archiveModifyRequest
    );

    @WebResult(name = "ArchiveSubmitResponse", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:archive", partName = "ArchiveSubmitResponse")
    @WebMethod
    public oasis.names.tc.dss._1_0.profiles.archive.ArchiveSubmitResponse archiveSubmit(
        @WebParam(partName = "ArchiveSubmitRequest", name = "ArchiveSubmitRequest", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:archive")
        oasis.names.tc.dss._1_0.profiles.archive.ArchiveSubmitRequest archiveSubmitRequest
    );

    @WebResult(name = "SignResponse", targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema", partName = "SignResponse")
    @WebMethod
    public oasis.names.tc.dss._1_0.core.schema.SignResponse sign(
        @WebParam(partName = "SignRequest", name = "SignRequest", targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema")
        oasis.names.tc.dss._1_0.core.schema.SignRequest signRequest
    );

    @WebResult(name = "CompoundResponse", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:compound", partName = "CompoundResponse")
    @WebMethod
    public oasis.names.tc.dss._1_0.profiles.compound.CompoundResponse compoundAsync(
        @WebParam(partName = "PendingRequest", name = "PendingRequest", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:asynchronousprocessing:1.0")
        oasis.names.tc.dss._1_0.profiles.asynchronousprocessing._1.PendingRequest pendingRequest
    );

    @WebResult(name = "CompoundResponse", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:compound", partName = "CompoundResponse")
    @WebMethod
    public oasis.names.tc.dss._1_0.profiles.compound.CompoundResponse compound(
        @WebParam(partName = "CompoundRequest", name = "CompoundRequest", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:compound")
        oasis.names.tc.dss._1_0.profiles.compound.CompoundRequest compoundRequest
    );

    @WebResult(name = "ArchiveVerifyResponse", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:archive", partName = "ArchiveVerifyResponse")
    @WebMethod
    public oasis.names.tc.dss._1_0.core.schema.ResponseBaseType archiveVerify(
        @WebParam(partName = "ArchiveVerifyRequest", name = "ArchiveVerifyRequest", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:archive")
        oasis.names.tc.dss._1_0.profiles.archive.ArchiveIdentifierRequest archiveVerifyRequest
    );

    @WebResult(name = "ArchiveRetrievalResponse", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:archive", partName = "ArchiveRetrievalResponse")
    @WebMethod
    public oasis.names.tc.dss._1_0.profiles.archive.ArchiveRetrievalResponse archiveRetrieval(
        @WebParam(partName = "ArchiveRetrievalRequest", name = "ArchiveRetrievalRequest", targetNamespace = "urn:oasis:names:tc:dss:1.0:profiles:archive")
        oasis.names.tc.dss._1_0.profiles.archive.ArchiveIdentifierRequest archiveRetrievalRequest
    );

    @WebResult(name = "VerifyResponse", targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema", partName = "VerifyResponse")
    @WebMethod
    public oasis.names.tc.dss._1_0.core.schema.VerifyResponse verify(
        @WebParam(partName = "VerifyRequest", name = "VerifyRequest", targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema")
        oasis.names.tc.dss._1_0.core.schema.VerifyRequest verifyRequest
    );
}
